### ISSUE TITLE
Added .gitattributes to exclude unneeded files for packages

### ISSUE THREAD

**Issue by elazar** [phergie/phergie-irc-generator#11]
See [this article](http://www.sitepoint.com/mastering-composer-tips-tricks/). Create a `.gitattributes` file in the root of the repo with entries for files like those under `tests`, `.travis.yml`, and others not needed by end users.

**Comment by tomzx** [comment]
Is the PR that was submitted @ https://github.com/phergie/phergie-irc-bot-react/issues/21 good enough to be cherry-picked in all the related projects?

**Comment by elazar** [comment]
Offhand, I think so. @svpernova09?

**Comment by svpernova09** [comment]
Yes, @tomzx we can use that `. gitattributes` everywhere.
